name: Feature Request
description: Suggest an improvement or new feature
title: "[Feature]: "
labels: ["enhancement"]

body:

  - type: input
    id: product_name
    attributes:
      label: Product Name
      placeholder: "Aphrils Widget Library - Widget Pack Name"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives Considered
    validations:
      required: false

